# The first entry is the official or most commonly used value, any other entries are also in use.
dasExtensions_by_sMediaType = {
  "application/x-bzpdf":                ["pdf"],
  "application/x-gzpdf":                ["pdf"],
  "application/gzip":                   ["gz"],
  "application/ico":                    ["ico"],
  "application/ecmascript":             ["es", "as"],
  "application/x-ecmascript":           ["es", "as"],
  "application/x-java-applet":          ["class"],
  "application/x-java-vm":              ["class"],
  "application/javascript":             ["js"],
  "application/x-javascript":           ["js"],
  "application/msword":                 ["doc", "dot", "rtf"],
  "application/x-navi-animation":       ["ani"],
  "application/octet-stream":           ["bin"],
  "application/ogg":                    ["ogg"],
  "application/pdf":                    ["pdf"],
  "application/x-pdf":                  ["pdf"],
  "application/rss+xml":                ["rss"],
  "application/rtf":                    ["rtf"],
  "application/x-sami":                 ["sami", "smi"],
  "application/smil":                   ["smi"],
  "application/smil+xml":               ["smi"],
  "application/x-shockwave-flash":      ["swf"],
  "application/x-vbs":                  ["vbs"],
  "application/vnd.ms-wpl":             ["wpl"],
  "application/x-win-bitmap":           ["cur"],
  "application/xhtml+xml":              ["xhtml", "xhtm", "xht"],
  "text/xsl":                           ["xsl"],
  "text/xslt":                          ["xslt"],
  "application/xml":                    ["xml"],
  "text/xml":                           ["xml"],
  
  "audio/3gpp":                         ["3gp"],
  "audio/3gpp2":                        ["3g2"],
  "audio/x-aiff":                       ["aif"],
  "audio/basic":                        ["snd"],
  "audio/x-matroska":                   ["mka"],
  "audio/mid":                          ["mid"],
  "audio/mp4":                          ["mp4"],
  "audio/mp4a-latm":                    ["m4a"],
  "audio/mpeg":                         ["mp3", "mp2", "mp1"],
  "audio/x-mpeg":                       ["mp3", "mp2", "mp1"],
  "audio/x-ms-wax":                     ["wax"],
  "audio/x-ms-wma":                     ["wma"],
  "audio/ogg":                          ["ogg"],
  "audio/wav":                          ["wav"],
  "audio/x-wav":                        ["wav"],
  
  "image/bmp":                          ["bmp"],
  "image/x-emf":                        ["emf"],
  "image/gif":                          ["gif"],
  "image/ico":                          ["ico"],
  "image/icon":                         ["ico"],
  "image/x-icon":                       ["ico"],
  "image/jpeg":                         ["jpeg", "jpg"],
  "image/pjpeg":                        ["jpeg", "jpg"],
  "image/png":                          ["png"],
  "image/rle":                          ["rle"],
  "image/svg+xml":                      ["svg"],
  "image/x-targa":                      ["tga"],
  "image/x-tga":                        ["tga"],
  "image/tiff":                         ["tif"],
  "image/x-tiff":                       ["tif"],
  "image/tiff-fx":                      ["tif"],
  "image/vnd.microsoft.icon":           ["ico"],
  "image/x-windows-bmp":                ["bmp"],
  "image/x-wmf":                        ["wmf"],
  "image/x-xbitmap":                    ["xbm"],
  "image/x-xbm":                        ["xbm"],
  "image/xbm":                          ["xbm"],
  "image/x-win-bitmap":                 ["cur"],
  
  "text/css":                           ["css"],
  "text/html":                          ["html", "htm"],
  "text/ico":                           ["ico"],
  "text/ecmascript":                    ["es", "as"],
  "text/x-ecmascript":                  ["es", "as"],
  "text/javascript":                    ["js"],
  "text/jscript":                       ["js"],
  "text/x-javascript":                  ["js"],
  "application/json":                   ["json"],
  "text/markdown":                      ["md"],
  "text/plain":                         ["txt"],
  "text/rtf":                           ["rtf"],
  "text/vbs":                           ["vbs"],
  "text/vbscript":                      ["vbs"],
  
  "video/3gpp":                         ["3gp"],
  "video/3gpp2":                        ["3g2"],
  "video/x-flv":                        ["flv"],
  "video/x-ivf":                        ["ivf"],
  "video/x-m4v":                        ["m4v"],
  "video/x-matroska":                   ["mkv", "mk3d", "mks"],
  "video/mp4":                          ["mp4"],
  "video/mpeg":                         ["mpeg", "mpg"],
  "video/x-msvideo":                    ["avi"],
  "video/x-ms-asf":                     ["asx"],
  "video/x-ms-wmv":                     ["wmv"],
  "video/x-ms-wmx":                     ["wmx"],
  "video/x-ms-wvx":                     ["wvx"],
  "video/ogg":                          ["ogv"],
  "video/quicktime":                    ["qt", "mov"],
  "video/webm":                         ["webm"],
};