# The first entry is the official or most commonly used value, any other entries are also in use.
dasMediaTypes_by_sExtension = {
  "3gp":      ["video/3gpp",                      "audio/3gpp"],
  "3g2":      ["video/3gpp2",                     "audio/3gpp2"],
  "aif":      ["audio/x-aiff"],
  "ani":      ["application/x-navi-animation"],
  "as":       ["application/ecmascript"],
  "asx":      ["video/x-ms-asf"],
  "avi":      ["video/x-msvideo"],
  "bmp":      ["image/bmp",                       "image/x-windows-bmp"],
  "class":    ["application/x-java-applet",       "application/x-java-vm"],
  "css":      ["text/css"],
  "cur":      ["image/vnd.microsoft.icon",        "image/x-win-bitmap", "application/x-win-bitmap"],
  "emf":      ["image/x-emf"],
  "es":       ["application/ecmascript",          "application/x-ecmascript", "text/ecmascript", "text/x-ecmascript"],
  "flv":      ["video/x-flv"],
  "gif":      ["image/gif"],
  "gz":       ["application/gzip"],
  "htm":      ["text/html"],
  "html":     ["text/html"],
  "ico":      ["image/vnd.microsoft.icon",        "text/ico", "image/ico", "image/icon", "application/ico", "image/x-icon"],
  "ivf":      ["video/x-ivf"],
  "jpg":      ["image/jpeg",                      "image/pjpeg"],
  "jpeg":     ["image/jpeg",                      "image/pjpeg"],
  "js":       ["application/javascript",          "application/x-javascript", "text/javascript", "text/jscript", "text/x-javascript"],
  "json":     ["application/json"],
  "m2v":      ["video/mpeg"],
  "m4a":      ["audio/mp4a-latm"],
  "m4v":      ["video/x-m4v"],
  "mid":      ["audio/mid"],
  "mk3d":     ["video/x-matroska"],
  "mka":      ["audio/x-matroska"],
  "mks":      ["video/x-matroska"],
  "mkv":      ["video/x-matroska"],
  "mov":      ["video/quicktime"],
  "mp3":      ["audio/mpeg"],
  "mp4":      ["video/mp4",                       "audio/mp4"],
  "mpa":      ["audio/mpeg",                      "video/mpeg"],
  "mpg":      ["video/mpeg",                      "application/mpeg", "application/x-mpeg"],
  "rle":      ["image/rle"],
  "ogg":      ["application/ogg"],
  "oga":      ["audio/ogg"],
  "ogv":      ["video/ogg"],
  "ogx":      ["application/ogg"],
  "opus":     ["audio/ogg"],
  "otf":      ["application/octet-stream"],
  "png":      ["image/png"],
  "pdf":      ["application/pdf",                 "application/x-pdf", "application/x-bzpdf", "application/x-gzpdf"],
  "qt":       ["video/quicktime"],
  "rss":      ["application/rss+xml"],
  "rtf":      ["text/rtf",                        "application/rtf", "application/msword"],
  "sami":     ["application/x-sami"],
  "smi":      ["application/smil",                "application/smil+xml", "application/x-sami"],
  "snd":      ["audio/basic"],
  "spx":      ["audio/ogg"],
  "svg":      ["image/svg+xml"],
  "swf":      ["application/x-shockwave-flash"],
  "tga":      ["image/x-tga",                     "image/x-targa"],
  "tif":      ["image/tiff",                      "image/x-tiff", "image/tiff-fx"],
  "ttf":      ["application/octet-stream"],
  "txt":      ["text/plain"],
  "vbs":      ["text/vbscript",                   "application/x-vbs", "text/vbs"],
  "wav":      ["audio/wav",                       "audio/x-wav"],
  "wax":      ["audio/x-ms-wax"],
  "webm":     ["video/webm"],
  "wma":      ["audio/x-ms-wma"],
  "wmf":      ["image/x-wmf"],
  "wmv":      ["audio/x-ms-wmv"],
  "wmx":      ["video/x-ms-wmx"],
  "wpl":      ["application/vnd.ms-wpl"],
  "wvx":      ["video/x-ms-wvx"],
  "xbm":      ["image/x-xbitmap",                 "image/x-xbm", "image/xbm"],
  "xhtml":    ["application/xhtml+xml"],
  "xsl":      ["application/xml",                 "text/xml", "text/xsl"],
  "xslt":     ["application/xml",                 "text/xml", "text/xslt"],
  "xml":      ["application/xml",                 "text/xml", "text/xml"],
};
